on:
  push:
    branches: main

jobs:
  import-data:
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::tidyverse
            any::duckdb
            any::arrow
            any::here

      - name: Check out repository
        uses: actions/checkout@v3
        
      - name: Import data
        run: Rscript -e 'source("scripts/01a-download_files_from_DataMart.R")'